version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: matchbot-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "4000:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql/"
    networks:
      - matchbot-network

  redis:
    image: redis:6-alpine
    container_name: matchbot-redis
    restart: unless-stopped
    tty: true
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "4001:6379"
    volumes:
      - ./redis:/data
    networks:
      - matchbot-network

  backend:
    container_name: matchbot-api
    restart: unless-stopped
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4002:9000"
    volumes:
      - "./api:/var/www/matchbot/api"
    networks:
      - matchbot-network

  frontend:
    container_name: matchbot-angular
    restart: unless-stopped
    tty: true
    build:
      context: ./angular
      dockerfile: Dockerfile.prod
    volumes:
      - "./nginx/frontend.prod.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4003:80"
    networks:
      - matchbot-network

networks:
  matchbot-network:
    driver: bridge
