version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: matchbot-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql/"
    networks:
      - app-network

  backend:
    container_name: matchbot-api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./api:/var/www"
    ports:
      - 9000:9000
    networks:
      - app-network

  frontend:
    container_name: matchbot-angular
    restart: unless-stopped
    tty: true
    build:
      context: ./angular
      dockerfile: Dockerfile
    volumes:
      - "./angular:/app"
      - "/app/node_modules"
    ports:
      - 9001:80
      - 9002:4200
      - 49153:49153
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
