FROM node:16 as base

WORKDIR /var/www/matchbot/angular

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=base /var/www/matchbot/angular/dist/matchbot /usr/share/nginx/html

EXPOSE 80
