FROM node:14 as base

WORKDIR /var/www/matchbot/angular

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=base /var/www/matchbot/angular/dist/matchbot /usr/share/nginx/html

EXPOSE 80
